create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.players(id) on delete cascade,
  message text not null,
  created_at timestamptz not null default now(),
  constraint chat_messages_message_length check (char_length(btrim(message)) between 1 and 500)
);

create index if not exists chat_messages_created_at_idx on public.chat_messages(created_at desc);
create index if not exists chat_messages_user_id_idx on public.chat_messages(user_id);

alter table public.chat_messages enable row level security;

revoke all on public.chat_messages from public, anon;
grant select, insert on public.chat_messages to authenticated;
grant usage, select on sequence public.chat_messages_id_seq to authenticated;

create policy chat_messages_read
on public.chat_messages
for select
to authenticated
using (true);

create policy chat_messages_insert_own
on public.chat_messages
for insert
to authenticated
with check (auth.uid() = user_id);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'chat_messages'
  ) then
    alter publication supabase_realtime add table public.chat_messages;
  end if;
end $$;
